# Generated by Django 3.2.16 on 2022-11-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
