# Generated by Django 3.2.16 on 2022-11-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
